# provider 配置

spring:
  profiles:
    active:
    - dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.96.93:3306/cloudDB01
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mycp.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client:  # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-id-address: true

info:
  app.name: mycp-microservicecloud-springcloudconfig02
  company.name: www.mycp.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
  
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.96.93:3306/cloudDB02
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mycp.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client:  # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-id-address: true

info:
  app.name: mycp-microservicecloud-springcloudconfig02
  company.name: www.mycp.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
  





